name: boostsecurity.io
on:
  workflow_dispatch:
  push:
    branches:
      - main-duplicate
  pull_request:
    branches:
      - main-duplicate
    types:
      - opened
      - synchronize
jobs:
  boost-sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: trivy-image
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/trivy-image
          api_token: ${{ secrets.BOOST_API_TOKEN }}
